### ISSUE TITLE
Add types for Typescript

### ISSUE THREAD

**Issue by Weffe** [lirantal/express-version-request#35]
Hello,

Just wanted to let you know that I just created a PR on the DefinitelyTyped repo that adds types for this package. Once it gets merged then Typescript users can just do `npm install @types/express-version-request`
 
PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30422

Example usage can be found in https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e3e64a37f82fafd9f9380136fdef4773b401287e/types/express-version-request/express-version-request-tests.ts

**Comment by lirantal** [comment]
That's awesome @Weffe, thanks for doing that! ❤️ 
Anything I can help with?

P.S would you like to PR to the repo instructions about types support?

**Comment by Weffe** [comment]
Hey, that was a quick response! There isn't anything to help it with as it's all on the DefinitelyTyped maintainers to review and approve the PR. Also, I can submit a PR to this repo stating how to use it with Typescript once the PR on DefinitelyTyped goes through :smiley:

**Comment by lirantal** [comment]
Awesome, that would be great!

**Comment by lirantal** [comment]
by the way @Weffe, this package is a sister one for https://github.com/lirantal/express-version-route which is where the real heavy lifting happens. Maybe you could also PR that for types?

**Comment by Weffe** [comment]
Yep, already created an issue in that repo with the types PR info

https://github.com/lirantal/express-version-route/issues/16

**Comment by lirantal** [comment]
Oh nice I missed that :-)
Thanks again!

**Comment by Weffe** [comment]
TypeScript instructions are added from PR #36 

This can be closed!
