### ISSUE TITLE
Feature: Support parsing version from Accept header

### ISSUE THREAD

**Issue by lirantal** [lirantal/express-version-request#7]
## Requirement
* Implement a method to set the version on the request object by parsing the accept header
* Add relevant unit tests
* Update README with example usage and relevant documentation

Hint: we suggest you name the new method `setVersionByAcceptHeader()`

### Description
`Accept` headers typically look like `Accept: application/json` to announce the requested media content type to be of JSON format, which is ubiquitous today with APIs.

To support an API version specified in the Accept header, it's general format should be specified as
`Accept: application/vnd.company+json;version=1.0.0` where:
1. `vnd.company` is any custom vendor prefix specified by the client
2. `+json` specified the requested format
3. `version` is then a parameter and value tuple for the accepted media type

* A generic rich specification of the Accept header: `Accept: audio/*; q=0.2, audio/basic`

### Optional
In addition to the above, you may optionally choose to implement the following:
* Support an additional (fallback) format to find and extract the version: `Accept: application/vnd.company-v1.0.0+json`
* Receive a function as argument that will be called with the Accept header and return the version so the method can support user-defined logic of how to set the version

**Comment by LiranBri** [comment]
is `Accept: application/vnd.company-v1.0.0+json` a standard?
[here](https://github.com/json-api/json-api/issues/432) someone suggested to use `Content-Type: application/vnd.api+json; json-api-version=1.0.0`

if it's not a standard, maybe it's better to support extracting the version with a custom regex. of course, if that implemented, then it's possible to build what you suggested on top of that

**Comment by lirantal** [comment]
Hi @LiranBri, thanks for jumping in!

A part of the HTTP [rfc](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html) refers to the accept header and its structure which aligns with the description I outlined. It is actually aligned with the example you referenced `Content-Type: application/vnd.api+json; json-api-version=1.0.0` where the parameter name for the version is `json-api-version` rather than just `version` but that's just semantics.

Also important to note that `Content-Type` header is associated with the response, not the request, which while important semantically it is not related to the API version request.

https://github.com/cerebris/jsonapi-resources/issues/874 is actually supporting the requirement described, and to give a reference for the optional accept header format support [github](https://developer.github.com/v3/media/#api-v3-media-type-and-the-future) chose to follow it. I agree that supporting the first format, and allowing a function callback is probably enough freedom.

**Comment by gagyibenedek** [comment]
I like the idea, will work on it.

**Comment by lirantal** [comment]
Closed by #8 !
