### ISSUE TITLE
Feature: Supporting converting non-semver to semver compatible

### ISSUE THREAD

**Issue by lirantal** [lirantal/express-version-request#9]
## Background
When the user's version is compared with the version set in the route definition using the `semver` library, it is expected that the user's specified version is semver-compatible.
Meaning, any non-compatible string is being ignored and thus the route version won't match and would result to a default route defined or continue to the next route/middleware.

## Requirement
The enhancement presented here will support converting a user input to semver compatible string. For example:
* Upon receiving a user version of `1.0` we will convert it to `1.0.0`
* Upon receiving a user version of `1.5` we will convert it to `1.5.0`

**Comment by gagyibenedek** [comment]
I'll jump on it!

**Comment by lirantal** [comment]
![](https://media.giphy.com/media/B5QDyiw4j8Xrq/giphy.gif)

**Comment by lirantal** [comment]
@gagyibenedek before you implement a parser function for this yourself, let's see if there's a package for this already as they might think of some unusual edge cases on handling this conversion. Maybe even the `semver` package itself has this.

**Comment by lirantal** [comment]
Closed by #12 !
